[pytest]
filterwarnings =
    ignore:Environment variable TORCH_FORCE_NO_WEIGHTS_ONLY_LOAD detected:UserWarning
    ignore:`torch.jit.script` is deprecated:DeprecationWarning
    ignore:Please use atoms.cell.cellpar instead:DeprecationWarning